const mainStyles = {
  container: { bgcolor: '#EEE', paddingBottom: { xs: '7px', md: 0 }, '& + .MuiList-root': { padding: 0 } },
  outerBox: { width: '77%', margin: '0 auto 10px' },
  listHeader: { bgcolor: '#eab200', padding: '16px', color: '#fff', marginTop: '1em' },
  listItem: {
    bgcolor: '#f8f8f8',
    padding: '7px 14px',
    margin: '2.8px 0',
    height: '59px',
    '&:hover': {
      backgroundColor: '#eab200',
      cursor: 'pointer',
    },
    '&:last-child': { marginBottom: 0 },
  },
  listItemButton: {
    paddingTop: 0,
    '&:hover': {
      backgroundColor: 'transparent',
    },
  },
  viewCountries: {
    bgcolor: '#eab200',
    color: '#fff',
    borderRadius: '0 0 10px 10px',
    fontSize: '12px',
    fontWeight: 300,
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#eab200',
      color: '#fff',
    },
  },
  gridContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'start',
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: '0px',
  },
  gridItemText: {
    '& .MuiTypography-root': {
      fontWeight: 300,
      fontSize: '14px',
      color: '#7f7f7f',
    },
  },
  gridItemPercentage: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: { sm: '0', md: '0 15px' },
  },
  linearProgress: {
    width: { xs: '70%', sm: '90%', md: '50%' },
    padding: { sm: '0' },
    height: '20px',
    borderRadius: '5px',
    fontWeight: 'bold',
    bgcolor: '#fff',
    boxShadow: 'inset 0 1px 2px rgb(0 0 0 / 10%)',
    '& .MuiLinearProgress-bar': {
      bgcolor: '#5a5898',
    },
  },
  select: {
    borderRadius: 0,
    borderLeft: '2px solid #fff',
    borderRight: '2px solid #fff',
    bgcolor: '#eee',
    '& .MuiSelect-select': {
      bgcolor: '#eee',
      fontSize: '18px',
      fontWeight: 400,
      borderBottom: 'none',
      padding: '8px 12px 25px',
    },
    '&:before': { borderBottom: 'none' },
    '&:hover': { borderBottom: 'none', bgcolor: '#eee' },
    '&:after': { borderBottom: 'none' },
  },
  menuItem: {
    fontSize: '14px',
    fontWeight: 600,
    '& ~ .MuiList-root': {
      padding: 0,
      margin: 0,
    },
    '&:hover': {
      backgroundColor: '#eab200',
      color: '#fff',
    },
  },
  menuListItem: {
    marginLeft: '20px',
    borderLeft: '1px solid #f2f2f2',
  },
  mainBarButton: {
    bgcolor: '#fff',
    color: '#000',
    marginTop: '7px',
    boxSizing: 'border-box',
    padding: '6px 12px',
    height: '34px',
    lineHeight: '34px',
    width: { xs: '100%', md: '126px', lg: '134px' },
    '&:hover': { bgcolor: '#e6e6e6', color: '#333', border: '1px solid #777' },
    '& .MuiButton-startIcon': {
      marginRight: '2px',
      color: '#eab200',
    },
    '& .MuiButton-startIcon>*:nth-of-type(1)': {
      fontSize: '16px',
    },
  },
  mainBarSwitch: {
    marginTop: { xs: '7px', md: 0 },
    paddingBottom: '7px',
    width: '100%',
    bgcolor: '#FFF',
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  mainBarGridItem: { display: 'flex', justifyContent: 'center' },

  mainBarGridItemText: { color: '#EAB200', textAlign: 'center', cursor: 'pointer' },
  formControl: { width: '100%' },
  modalContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 500,
    bgcolor: '#f2f2f2',

    boxShadow: 24,
    borderRadius: '5px',
    border: '1.5em solid #fff',
    p: 4,
  },
  modalHeader: { width: '100%', display: 'flex', justifyContent: 'space-between' },
  modalHeaderText: { fontSize: '18px', fontWeight: 700, color: '#333' },
  modalHeaderText2: { fontSize: '95%', fontWeight: 300, color: '#777' },
  closeButton: {
    borderRadius: '50px',
    minWidth: '40px',
    width: '40px',
    height: '40px',
    padding: 0,
    margin: -6,
    bgcolor: '#fff',
    color: '#000',
    fontSize: '18px',
    fontWeight: 700,
    '&:hover': { bgcolor: '#e6e6e6', color: '#333', border: '1px solid #777' },
  },
  resetButton: {
    width: '100%',
    display: 'flex',
    justifyContent: 'end',
    padding: '50px 0 20px 0',
  },
  sliderContainer: { display: 'flex', flexDirection: 'column', alignItems: 'space-between', marginBottom: '40px' },
  slider: {
    width: '100%',
    padding: '10px 0',
    color: 'success.main',
    '& .MuiSlider-thumb': {
      borderRadius: '3px',
      backgroundColor: '#EAB200',
      width: '12px',
    },
    '& .MuiSlider-track': {
      backgroundColor: '#fff',
      height: '5px',
      border: '1px solid #777',
      borderRadius: '3px',
    },
    '& .MuiSlider-rail': {
      backgroundColor: '#fff',
      border: '1px solid #777',
      height: '5px',
      borderRadius: '3px',
    },
  },
  sliderTextContainer: { width: '100%', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  sliderText: { fontWeight: 600, margin: 0 },
  summaryContainer: { textAlign: 'right', fontWeight: 600 },
};
export { mainStyles };
